"""Added missing field ip to AP table

Revision ID: 1a71d90a35d5
Revises: 07bfc4405d71
Create Date: 2024-06-11 22:29:56.612015

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a71d90a35d5"
down_revision: Union[str, None] = "07bfc4405d71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "access_points", sa.Column("ip", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("access_points", "ip")
    # ### end Alembic commands ###
