"""test

Revision ID: 591453ee9bd8
Revises: 71c3f5e5c075
Create Date: 2024-06-09 14:08:39.063966

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "591453ee9bd8"
down_revision: Union[str, None] = "71c3f5e5c075"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ap",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "network",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("ssid", sa.String(), nullable=True),
        sa.Column("country_code", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "ap_network_connector",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ap_id", sa.Integer(), nullable=False),
        sa.Column("network_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ap_id"],
            ["ap.id"],
        ),
        sa.ForeignKeyConstraint(
            ["network_id"],
            ["network.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ap_network_connector")
    op.drop_table("network")
    op.drop_table("ap")
    # ### end Alembic commands ###
