"""Added nullable password field to Networks

Revision ID: 6112ff888c47
Revises: 7d4b4a2a4846
Create Date: 2024-06-30 14:05:53.299744

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6112ff888c47"
down_revision: Union[str, None] = "7d4b4a2a4846"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "networks", sa.Column("password", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("networks", "password")
    # ### end Alembic commands ###
