"""Fixed Security-MacACL relationship

Revision ID: 7d4b4a2a4846
Revises: f2c95e62242b
Create Date: 2024-06-30 14:01:49.440846

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d4b4a2a4846"
down_revision: Union[str, None] = "f2c95e62242b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
