"""Added name fields.

Revision ID: e54ac155e6d6
Revises: 9b2979b5936d
Create Date: 2024-06-30 19:09:14.845945

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e54ac155e6d6"
down_revision: Union[str, None] = "9b2979b5936d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mac_acls", sa.Column("name", sa.String(), nullable=False))
    op.create_unique_constraint(None, "mac_acls", ["name"])
    op.add_column("security", sa.Column("name", sa.String(), nullable=False))
    op.create_unique_constraint(None, "security", ["name"])
    op.add_column("wireless", sa.Column("name", sa.String(), nullable=False))
    op.create_unique_constraint(None, "wireless", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "wireless", type_="unique")
    op.drop_column("wireless", "name")
    op.drop_constraint(None, "security", type_="unique")
    op.drop_column("security", "name")
    op.drop_constraint(None, "mac_acls", type_="unique")
    op.drop_column("mac_acls", "name")
    # ### end Alembic commands ###
