"""Changed mac_acl to list

Revision ID: f2c95e62242b
Revises: e31e01fbbd6a
Create Date: 2024-06-29 22:25:11.163358

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2c95e62242b"
down_revision: Union[str, None] = "e31e01fbbd6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
